### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by jsbmusic821** [DevDungeon/Cathy#12]
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/discord/client.py", line 255, in _run_event
    await coro(*args, **kwargs)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/cathy/cathy.py", line 55, in on_ready
    yield from self.discord_client.change_presence(game=discord.Game(name='Chatting with Humans'))
TypeError: change_presence() got an unexpected keyword argument 'game'

I even removed that and tried it again still the same

**Comment by NanoDano** [comment]
You are using the wrong version of Python and the wrong version of discord.py. Please read the documentation linked in the README.
