### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by arit123** [DevDungeon/Cathy#14]
"Traceback (most recent call last):
  File "C:\Users\telfo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\telfo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cathy\cathy.py", line 74, in on_message
    yield from self.discord_client.send_typing(message.channel)
AttributeError: 'Bot' object has no attribute 'send_typing'"
whenever i try to run the bot this is what i get.

**Comment by NanoDano** [comment]
Bad version combinations
