### ISSUE TITLE
The issue on message send and game text set!

### ISSUE THREAD

**Issue by MarcelDutko** [DevDungeon/Cathy#8]
When I say HEY in discord:
Message: Hey
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 255, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\cathy-1.1.2-py3.7.egg\cathy\cathy.py", line 74, in on_message
    yield from self.discord_client.send_typing(message.channel)
AttributeError: 'Bot' object has no attribute 'send_typing'

Please help. This is so important

**Comment by NanoDano** [comment]
Updated the `setup.py` file to specify Python version must be < 3.7 and discord.py must be 0.16.12.
