### ISSUE TITLE
pip installing

### ISSUE THREAD

**Issue by seanjhatch** [DevDungeon/Cathy#9]
`sudo pip3 install Cathy' gives this error:

```Collecting cathy
  Downloading https://files.pythonhosted.org/packages/38/7c/bc9722c9656573674b7222944707e36b069e5d0cfa76b51f60095cde1772/cathy-1.1.3.tar.gz (1.5MB)
    100% |████████████████████████████████| 1.5MB 727kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rfwkhsg_/cathy/setup.py", line 26, in <module>
        install_requires=open('requirements.txt').read().splitlines(),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rfwkhsg_/cathy/```

**Comment by seanjhatch** [comment]
normal 'pip install Cathy' also returns the same error.

**Comment by NanoDano** [comment]
try again now `pip3 install cathy --no-cache-dir`
